services:
  - type: web
    name: chazefashion
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn chazefashion_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: chazefashion_project.settings
      - key: PYTHON_VERSION
        value: 3.11.9
