services:
  - type: web
    name: chazefashion
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: "gunicorn ChazeFashion.ChazeFashion.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ChazeFashion.ChazeFashion.settings
      - key: PYTHON_VERSION
        value: 3.11.9
